[Thu, 09 Jan 2020 16:47:21] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:21] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104183460>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:22] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:22] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104183ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:23] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:23] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104183400>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:24] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:24] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041a2490>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:25] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:25] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041a2c40>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:26] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:26] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ad430>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:27] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:27] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041adbe0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:28] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:28] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041a2910>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:29] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:29] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041a2490>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:30] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:30] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416d460>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:31] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:31] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104183b50>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:32] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:32] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041adcd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:33] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:33] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ad160>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:34] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:34] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1052063d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:35] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:35] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041835e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:36] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:36] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104183eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:37] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:37] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416d8e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:38] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:38] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ad5b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:39] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:39] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ad580>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:40] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:40] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105206c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:41] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:41] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105204400>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:42] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:42] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416d1f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:43] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:43] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ad910>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:44] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:44] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041ad610>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:45] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 16:47:45] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105206ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 16:47:46] - shutdown_hook - Kafka producer closed successfully!
[Thu, 09 Jan 2020 21:36:55] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:36:55] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e520>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:36:56] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:36:56] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914eca0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:36:57] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:36:57] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:36:58] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:36:58] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916d490>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:36:59] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:36:59] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916dc40>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:00] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:00] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109178430>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:01] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:01] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109178be0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:02] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:02] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916d910>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:03] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:03] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916d490>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:04] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:04] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138460>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:05] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:05] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914eb50>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:06] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:06] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109178cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:07] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:07] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109178520>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:08] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:08] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091943d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:09] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:09] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914ea00>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:10] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:10] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091385b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:11] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:11] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109178070>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:12] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:12] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109178940>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:13] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:13] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091946d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:14] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:14] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:15] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:15] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191400>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:16] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:16] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138700>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:17] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:17] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109178e20>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:18] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:18] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091782b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:19] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:19] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:20] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:20] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194520>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:21] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:21] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e790>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:22] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:22] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e2b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:23] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:23] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191bb0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:24] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:24] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194280>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:25] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:25] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091949d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:26] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:26] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091388e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:27] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:27] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091919d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:28] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:28] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191df0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:29] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:29] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:30] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:30] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917ad90>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:31] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:31] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091912e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:32] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:32] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191160>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:33] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:33] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914ea00>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:34] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:34] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914ec10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:35] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:35] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:36] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:36] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:37] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:37] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916cd90>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:38] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:38] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e880>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:39] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:39] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138b20>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:40] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:40] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916ce80>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:41] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:41] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a190>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:42] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:42] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917aa90>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:43] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:43] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091945e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:44] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:44] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194d90>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:45] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:45] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:46] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:46] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c5b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:47] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:47] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138880>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:48] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:48] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914eb20>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:49] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:49] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e6d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:50] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:50] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091940d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:51] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:51] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091915e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:52] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:52] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914ed90>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:53] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:53] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091385b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:54] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:54] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c160>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:55] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:55] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:56] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:56] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917aee0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:57] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:57] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191370>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:58] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:58] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917aca0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:37:59] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:37:59] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:00] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:00] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916cc40>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:01] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:01] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e1f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:02] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:02] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138610>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:03] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:03] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194640>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:04] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:04] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191b20>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:05] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:05] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191d90>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:06] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:06] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091389a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:07] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:07] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914eca0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:08] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:08] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916cc10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:09] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:09] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c250>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:10] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:10] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a2e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:11] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:11] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a670>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:12] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:12] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091917f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:13] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:14] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a2e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:15] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:15] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c8e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:16] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:16] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091380a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:17] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:17] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e400>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:18] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:18] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:19] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:19] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091945e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:20] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:20] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191d00>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:21] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:21] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e490>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:22] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:22] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e880>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:23] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:23] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916cc70>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:24] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:24] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c640>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:25] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:25] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a880>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:26] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:26] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191040>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:27] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:27] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1580>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:28] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:28] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a880>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:29] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:29] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c640>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:30] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:30] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138940>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:31] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:31] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e550>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:32] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:32] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194f10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:33] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:33] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1310>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:34] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:34] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194730>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:35] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:35] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914ef10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:36] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:36] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091387f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:37] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:37] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c280>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:38] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:38] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a700>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:39] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:39] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917aac0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:40] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:40] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1880>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:41] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:41] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1df0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:42] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:42] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917adf0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:43] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:43] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916cb80>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:44] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:44] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e8e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:45] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:45] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914ef70>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:46] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:46] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091387f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:47] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:47] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109194be0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:48] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:48] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1790>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:49] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:49] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138070>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:50] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:50] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914efa0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:51] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:51] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a910>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:52] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:52] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a580>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:53] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:53] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916cbe0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:54] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:54] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1f10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:55] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:55] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1d60>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:56] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:56] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091919d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:57] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:57] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191af0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:58] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:58] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:38:59] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:38:59] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917aaf0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:00] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:00] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e400>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:01] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:01] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c100>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:02] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:02] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916ca60>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:03] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:03] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e550>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:04] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:04] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917ab20>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:05] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:05] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191820>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:06] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:06] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191970>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:07] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:07] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138820>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:08] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:08] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c340>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:09] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:09] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1190>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:10] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:10] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091385e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:11] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:11] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191bb0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:12] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:12] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917aa60>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:13] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:13] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a6a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:14] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:14] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914ed90>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:15] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:15] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914ebb0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:16] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:16] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1c70>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:17] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:17] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917ab50>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:18] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:18] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a6d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:19] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:19] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091912b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:20] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:20] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191c70>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:21] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:21] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138880>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:22] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:22] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1f40>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:23] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:23] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a6670>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:24] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:24] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138700>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:25] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:25] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091915e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:26] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:26] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a2e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:27] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:27] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917af40>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:28] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:28] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914edf0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:29] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:29] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a64f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:30] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:30] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a6e20>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:31] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:31] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:32] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:32] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a460>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:33] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:33] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191310>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:34] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:34] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191a00>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:35] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:35] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138580>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:36] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:36] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a64c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:37] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:37] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091ac610>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:38] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:38] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091389a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:39] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:39] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191a00>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:40] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:40] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:41] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:41] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a340>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:42] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:42] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e1c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:43] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:43] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091ac3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:44] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:44] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914e550>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:45] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:45] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a640>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:46] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:46] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a8b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:47] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:47] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10916c0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:48] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:48] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091911f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:49] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:49] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191040>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:50] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:50] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091acc10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:51] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:51] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091acdc0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:52] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:52] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191f40>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:53] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:53] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1730>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:54] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:54] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091388e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:55] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:55] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917aa90>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:56] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:56] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a4c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:57] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:57] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10914ec70>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:58] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:58] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091ac820>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:39:59] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:39:59] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a280>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:00] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:00] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917af10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:01] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:01] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091387f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:02] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:02] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191a30>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:03] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:03] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091917c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:04] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:04] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a6520>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:05] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:05] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091acd30>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:06] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:06] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191b50>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:07] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:07] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091911f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:08] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:08] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138760>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:09] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:09] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a970>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:10] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:10] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a070>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:11] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:11] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091ac040>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:12] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:13] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091b85b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:14] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:14] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917a940>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:15] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:15] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10917ac10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:16] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:16] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138730>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:17] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:17] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191be0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:18] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:18] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109191310>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:19] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:19] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091b8340>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:20] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:20] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091ac1f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:21] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:21] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091acac0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:22] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:22] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109138550>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:23] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:23] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a6d30>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:24] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:24] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a6370>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:25] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:25] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1580>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:26] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:26] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091914c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:27] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:27] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091913d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:28] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:28] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a1b20>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:29] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:40:29] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1091a6190>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:40:29] - shutdown_hook - Kafka producer closed successfully!
[Thu, 09 Jan 2020 21:44:50] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:44:50] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b36520>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:44:52] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:44:52] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b36ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:44:53] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:44:53] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b363a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:44:54] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:44:54] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b56490>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:44:55] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:44:55] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b56c40>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:44:56] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:44:56] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b60430>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:44:57] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:44:57] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b60be0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:44:58] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:44:58] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b56910>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:44:59] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:44:59] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b56490>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:45:00] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:45:00] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b20460>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:45:01] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:45:01] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b36b50>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:45:02] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:45:02] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b60cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:45:03] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:45:03] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b60520>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:45:04] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:45:04] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b7c3d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:45:05] - fetch_weather_data - Start to fetch weather data.
[Thu, 09 Jan 2020 21:45:05] - fetch_weather_data - Failed to fetch weather data because HTTPConnectionPool(host='localhost', port=3001): Max retries exceeded with url: /weather (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104b36a00>: Failed to establish a new connection: [Errno 61] Connection refused'))
[Thu, 09 Jan 2020 21:45:05] - shutdown_hook - Kafka producer closed successfully!
